<?php
use oxide\helper\_html;



?>
<!DOCTYPE html>
<html lang="en-US">	
   <head>
		<meta charset="utf-8" />
      <!-- using bootstrap framework -->
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
      <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>		
	</head>
	
	<body class="container">
      <header>
         <h1>Oxide framework <small>A modern PHP framework.</small></h1>
         <nav>
            <ul class="nav nav-tabs">
               <li role="presentation" class="active"><a href="/">Home</a></li>
               <li role="presentation"><a href="/">Overview</a></li>
               <li role="presentation"><a href="/">Quick start</a></li>
               <li role="presentation"><a href="/">Architecture</a></li>
               <li role="presentation"><a href="/">API</a></li>
               <li role="presentation"><a href="/">Demo</a></li>
               <li role="presentation"><a href="/">Download</a></li>
            </ul>
         </nav>
      </header>
      
      <div>
         <?= $this->getPartial(NULL); ?>
      </div>
      
      <br/>
      <footer>
         <hr/>
         <p>copyright phpoxide @ <a href="http://phpoxide.googlecode.com">http://phpoxide.googlecode.com</a></p>
         <p>Using <a href="http://getbootstrap.com">Bootstrap</a> CSS framework.</p>
      </footer>
	</body>
</html>
