<?php

namespace oxide\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-31 at 04:25:27.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

   /**
    * @var Request
    */
   protected $object;

   /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    */
   protected function setUp() {
      $this->object = new Request();
   }

   /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    */
   protected function tearDown() {
      
   }

   public function testServerRequest() {
      $request = Server::currentRequest();
      
      
      
   }
   
   /**
    * 
    */
   public function testSettingNewUrl() {
      $request = $this->object;
      
      $testUrl = 'http://google.com';
      $request->setUrl($testUrl);
      
      // first making sure that url is acutally setting
      $this->assertEquals($testUrl, $request->getUrl());
   }
   
   /**
    * 
    */
   public function testIsSecured() {
      $this->object->setUrl('https://apple.com');
      $this->assertTrue($this->object->isSecured(), 'Secured site');
      
      $this->object->setUrl('http://apple.com');
      $this->assertTrue(!$this->object->isSecured(), 'Unsecured site');
   }
   
   
}
